<?php
/**
 * @file
 * This module provides publication-related functionality (i.e. Views theming)
 */

/**
 * Implements hook_theme
 */
function hc_publications_theme($existing, $type, $theme, $path) {
  return array(
    // main catalog pages
    'views_view_field__productzoeken__nothing' => array( 
      'arguments' => array('view' => FALSE, 'field' => FALSE, 'row' => FALSE),
      'original hook' => 'views_view_field',
    ),
  );
}